### ISSUE TITLE
tax error at 'ganglia_ip'; expected '}' at /etc/puppet/manifests/site.pp:96 on node puppet.com

### ISSUE THREAD

**Issue by mh54** [jhoblitt/puppet-ganglia#39] opened 2015-01-20 08:30 UTC
I'm new to puppet. When I install the ganglia module I keep getting the following error
tax error at 'ganglia_ip'; expected '}' at /etc/puppet/manifests/site.pp:96 on node puppet.com
I checked all brackets seem to match,Here's a copy of my site.pp.

 
class{ 'ganglia::gmond':
  cluster_name       => 'puppet',
  cluster_owner      => 'none',
  cluster_latlong    => 'N32.2332147 W110.9481163',
  cluster_url        => 'www.example.org',
  host_location      => 'example computer room',
udp_recv_channel   => $udp_recv_channel,
udp_send_channel   => $udp_send_channel,
  tcp_accept_channel => $tcp_accept_channel,
}

$clusters = [
  {
    name     => 'puppet',
    address  => ['node001.com'],
  },
]
 class{ 'ganglia::gmetad':
  clusters => $clusters,
  gridname => 'my grid',
}
class{ 'ganglia::web': }
 class{ 'ganglia::web':
  $ganglia_ip = '127.0.0.1',
  $ganglia_port = 8652,
}

**Comment by jhoblitt** [comment] 2015-01-26 16:30
Appears to be a duplicate of #38.

**Closed by jhoblitt** 2015-01-26 16:30 UTC
